title:  A space for Ketul Gupta to share his work
description: A Computer Science graduate passionate about data and full stack engineering.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman